### ISSUE TITLE
FailedToOpenSocket: Was there a typo in the url or port?

### ISSUE THREAD

**Issue by namimo** [coollabsio/next-image-transformation#16]
Build a new image to use latest version of bun which fixes this issue.

And one more thing. On error response set the header to not store cache.

**Comment by japurillo** [comment]
2025-02-03T12:52:17.862675919Z FailedToOpenSocket: Was there a typo in the url or port?
2025-02-03T12:52:17.862760740Z  path: "http://imgproxy:8080/pr:sharp/resize:fill:128:0/q:75/plain/https://[DEPRECATED]/image/upload/c_pad,f_auto,h_80,w_80/v1/images/File.png"

Also getting the same error. The thing is, after restarting, it will work again...... for a day or two... or sometimes longer.

**Comment by ColeTownsend** [comment]
@namimo or @japurillo did you manage to rebuild this image?

**Comment by namimo** [comment]
I used docker compose to build fresh image from git source. 

```yml
services:
  api:
    build: 'https://github.com/coollabsio/next-image-transformation.git'
    ports:
      - '3000'
    environment:
      - NODE_ENV=production
      - 'ALLOWED_REMOTE_DOMAINS=*'
      - 'IMGPROXY_URL=http://imgproxy:8080'
    healthcheck:
      test: 'wget -qO- http://localhost:3000/health || exit 1'
      interval: 2s
      timeout: 10s
      retries: 5
    depends_on:
      imgproxy:
        condition: service_healthy
    image: ''
  imgproxy:
    image: darthsim/imgproxy
    environment:
      - IMGPROXY_ENABLE_WEBP_DETECTION=true
      - IMGPROXY_ENABLE_AVIF_DETECTION=true
      - IMGPROXY_JPEG_PROGRESSIVE=true
      - IMGPROXY_USE_ETAG=true
    healthcheck:
      test:
        - CMD
        - imgproxy
        - health
      interval: 2s
      timeout: 10s
      retries: 5
```
